version: '3'

services:
  nodejs:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

